language: java
before_install:
- sudo apt-get update
- sudo apt-get install sshpass
install: mvn install
jdk:
- oraclejdk8
env:
  global:
    secure: 6xTKhcqIuXZlz5cXLKT1YB36P1rmNXwW4mugRItUt7XA9IdFT8e4Q7P+5Oj8uNo0WzlSHj7mzfEvqKVsVIuOCaW7M6ztz/PVgVEUWMdQb+2lIviV38sNq+et1C0PyaU0WWwKsi0ZWd2YWlFzmmR/BI43E3dXO5R2D9SuJY8BGW6ic5v7D4mIOGa4FmBYDuO5Xky6tLfNZZd98WS9CTZnKVw6UilveeHNm+/AAMZuk20dH0SSCQiUupmA8z0mJGlzYEVSkchL0fSQTuWYdetFYO/pHMaHgg3icCwhdhxzWKpd8UndiRNvfDBjWKztACPJhjk8Qu9//l8ikKM7O9yv1fdV0oAcwSoyzsCGeilcdTzD1aZZEjD/jcjv04ND0Lvb+dT6XWrx33s0YKd9v8sgIwg9kTSvBDA/qZrp7I94cD/5pVE3VtdMqcjPovF7njUcg0edauceisHrlW0FMJMAsN+MWvFgrsTc/WrqiR1pS07Jf1ijB+IvbUxM5KRZLaqXtC7LN0btdF4Fm30QfYTeHEwEi0UgEB1WxGtekKs1njUu9Vhs7I93gCs1CZ7Pp4X3IoZlVp6LWX/rEMmalp9ULUpECrOh24zLk8oZXobG6t5ZVheJAHLbmUhLnmHHaJugQqDDaAtPjmQWuBOBruC4UrGJxZMytXgRFbm501704Bw=
